- name: Kalliope yandex tts install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: yandex_speech
        version: 0.4
